### ISSUE TITLE
OAuthTokenCredential expiresIn() computation error (sec vs millisec)

### ISSUE THREAD

**Issue by fabiduch** [paypal/sdk-core-java#45]
Hi,

there is a mistake in the way the OAuthTokenCredential expiresIn variable is managed.

Indeed, the "expires_in" returns by paypal is in seconds so when current time is added or substract, current time should be divided by 1000 as express in milliseconds (or expires should be multiply by 1000) to be consistent in the units!

Correct code is for example :

// Save expiry date
long tokenLifeTime = jsonElement.getAsJsonObject().get("expires_in").getAsLong();
expires = ( new Date().getTime() / 1000 ) + tokenLifeTime;

AND after :

public long expiresIn() {
    return expires -  ( new java.util.Date().getTime() / 1000 );
}

or you could simply multiply the tokenLifeTime by 1000 and then considering that the expiresIn() method returns milliseconds (may it's the best way to do).

Regards

**Comment by fabiduch** [comment]
Sorry I don't have a dev environment available to pull request... Have you the possibility to correct it ?  thanks

**Comment by juwlee** [comment]
@fabiduch the fix is available in the latest version of [PayPal-Java-SDK](https://github.com/paypal/PayPal-Java-SDK) along with other improvements and feature additions. Are you using this SDK core alone or an old version of the REST SDK?

**Comment by fabiduch** [comment]
Hi, we used the 0.12.2 version so far.  So we'll updated to the lastest one (1.2.3) as it seems that a lot of changes as been performed since then. Thanks.
