### ISSUE TITLE
IPN transaction verification fails if behind a firewall (using proxy)

### ISSUE THREAD

**Issue by andrejbagon** [paypal/sdk-core-java#49]
if IPN application is behind a firewall it does not verify the transaction. It should use a proxy, but proxy is ignored by IPNMessage.

The fix is for file: src/main/java/com/paypal/ipn/IPNMessage.java

in method initialize() we add at the end:

if (Boolean.valueOf(configurationMap.get(Constants.USE_HTTP_PROXY))) {
httpConfiguration.setProxyHost(configurationMap.get(Constants.HTTP_PROXY_HOST));
httpConfiguration.setProxyPort(Integer.parseInt(configurationMap.get(Constants.HTTP_PROXY_PORT)));
httpConfiguration.setProxySet(Boolean.valueOf(configurationMap.get(Constants.USE_HTTP_PROXY)));
}

**Comment by juwlee** [comment]
@andrejbagon thanks for the input. The fix #50 has been released.
