### ISSUE TITLE
Paypal Core dose not work under Websphere IBM

### ISSUE THREAD

**Issue by aumerhadi** [paypal/sdk-core-java#51]
Hi
I am working on project using Paypal core jar file, the code is work fine under tomcat server, but it fail when I deployed it to Websphere. (com.paypal.exception.SSLConfigurationException: SunJSSE)

After debug my code I found you are using "SunJSSE", and it's not supported under websphere (WAS use IBM JRE, not Oracle (SUN) JRE)

By looking at code on github, I notice "SunJSSE" hard coded at SSLUtil.java. (line # 85)

To fix this issue you will need to change SUNJSSE to IBMJCE, and the code will work fine under WAS. 

If you can add this as option with the configuration, so users can change it based on web server.

**Comment by juwlee** [comment]
@aumerhadi thanks for your feedback. The fix was released. Now you can [set it from config file](https://github.com/paypal/sdk-core-java/blob/master/src/test/resources/sdk_config.properties#L43)
