### ISSUE TITLE
1.6.9 broken build Could not initialize class com.paypal.core.SSLUtil on Google App Engine

### ISSUE THREAD

**Issue by dincek** [paypal/sdk-core-java#56]
java.lang.NoClassDefFoundError: Could not initialize class com.paypal.core.SSLUtil
	at com.paypal.core.DefaultHttpConnection.<init>(DefaultHttpConnection.java:35)
	at com.paypal.core.ConnectionManager.getConnection(ConnectionManager.java:37)
	at com.paypal.ipn.IPNMessage.validate(IPNMessage.java:185)

**Comment by dincek** [comment]
Hi,

problem is with IPNMessage -> validate(), even when I passed custom config map with http.GoogleAppEngine = true, validate() function still chooses DefaultHttpConnection instead of GoogleAppEngineHttpConnection and I cannot find solution to fix that with just config.

Please help.

Stack:
Nested in java.lang.ExceptionInInitializerError:
java.lang.NullPointerException
	at com.paypal.sdk.util.ResourceLoader.searchClasspath(ResourceLoader.java:65)
	at com.paypal.sdk.util.ResourceLoader.getInputStream(ResourceLoader.java:49)
	at com.paypal.core.ConfigManager.<init>(ConfigManager.java:88)
	at com.paypal.core.ConfigManager.getInstance(ConfigManager.java:106)
	at com.paypal.core.SSLUtil.<clinit>(SSLUtil.java:43)
	at com.paypal.core.DefaultHttpConnection.<init>(DefaultHttpConnection.java:35)
	at com.paypal.core.ConnectionManager.getConnection(ConnectionManager.java:37)
	at com.paypal.ipn.IPNMessage.validate(IPNMessage.java:185)

**Comment by juwlee** [comment]
@dincek can you clarify a few things?
- Are you running this on GAE?
- How did you get the two different stack dumps?
- Is Java classpath(`java.class.path`) set in your env?

**Comment by dincek** [comment]
Hi,

1. Yes, running on GAE
2. First one was when I did not used http.GoogleAppEngine = true for all Paypal calls
3. Should be

The problem only remains for IPNMessage, i already patched my local IPNMessage class with two additional lines so that IPNMessage.validate() works and uses GoogleAppEngineHttpConnection instead of default, please check out class below against IPNMessage and patch it please. Fixes are in function initialize() and validate().

package com.videodeck.services.paypal;

import java.net.URL;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.servlet.http.HttpServletRequest;

import com.paypal.core.ConfigManager;
import com.paypal.core.ConnectionManager;
import com.paypal.core.Constants;
import com.paypal.core.HttpConfiguration;
import com.paypal.core.HttpConnection;
import com.paypal.core.LoggingManager;
import com.paypal.core.SDKUtil;

public class IPNMessageGAE {

	private static final Logger log = Logger.getLogger(IPNMessageGAE.class.getName());

	private static final long serialVersionUID = -7187275404183441828L;
	private static final String ENCODING = "windows-1252";

	private Map<String, String> ipnMap = new HashMap<String, String>();
	private Map<String, String> configurationMap = null;
	private HttpConfiguration httpConfiguration = null;
	private String ipnEndpoint = Constants.EMPTY_STRING;
	private boolean isIpnVerified = false;
	private StringBuffer payload;

	/**
	 * Populates HttpConfiguration with connection specifics parameters
	 */
	private void initialize() {
		httpConfiguration = new HttpConfiguration();
		ipnEndpoint = getIPNEndpoint();
		httpConfiguration.setEndPointUrl(ipnEndpoint);
		httpConfiguration.setConnectionTimeout(Integer
						.parseInt(configurationMap
										.get(Constants.HTTP_CONNECTION_TIMEOUT)));
		httpConfiguration.setMaxRetry(Integer.parseInt(configurationMap
						.get(Constants.HTTP_CONNECTION_RETRY)));
		httpConfiguration.setReadTimeout(Integer.parseInt(configurationMap
						.get(Constants.HTTP_CONNECTION_READ_TIMEOUT)));
		httpConfiguration.setMaxHttpConnection(Integer
						.parseInt(configurationMap
										.get(Constants.HTTP_CONNECTION_MAX_CONNECTION)));
		if (Boolean.valueOf(configurationMap.get(Constants.USE_HTTP_PROXY))) {
			httpConfiguration.setProxyHost(configurationMap.get(Constants.HTTP_PROXY_HOST));
			httpConfiguration.setProxyPort(Integer.parseInt(configurationMap.get(Constants.HTTP_PROXY_PORT)));
			httpConfiguration.setProxySet(Boolean.valueOf(configurationMap.get(Constants.USE_HTTP_PROXY)));
			httpConfiguration.setProxyUserName(configurationMap.get(Constants.HTTP_PROXY_USERNAME));
			httpConfiguration.setProxyPassword(configurationMap.get(Constants.HTTP_PROXY_PASSWORD));
		}
		httpConfiguration.setGoogleAppEngine(Boolean.valueOf(configurationMap.get(Constants.GOOGLE_APP_ENGINE)));
	}

	/**
	 * Constructs {@link IPNMessageGAE} using the given {@link HttpServletRequest}
	 * to retrieve the name and value {@link Map}.
	 *
	 * @param request
	 *            {@link HttpServletRequest} object received from PayPal IPN
	 *            call back.
	 */
	public IPNMessageGAE(HttpServletRequest request) {
		this(request.getParameterMap(), true);
	}

	/**
	 * Constructs {@link IPNMessageGAE} using the given {@link Map} for name and
	 * values.
	 *
	 * @param ipnMap
	 *            {@link Map} representing IPN name/value pair
	 *
	 * @param decoded boolean Representing if the value has been decoded
	 */
	public IPNMessageGAE(Map<String, String[]> ipnMap, boolean decoded) {
		this(ipnMap, ConfigManager.getInstance().getConfigurationMap(), decoded);
	}

	/**
	 * Constructs {@link IPNMessageGAE} using the given {@link Map} for name and
	 * values.
	 *
	 * @param ipnMap
	 *            {@link Map} representing IPN name/value pair
	 */
	public IPNMessageGAE(Map<String, String[]> ipnMap) {
		this(ipnMap, ConfigManager.getInstance().getConfigurationMap());
	}

	/**
	 * Constructs {@link IPNMessageGAE} using the given {@link HttpServletRequest}
	 * to retrieve the name and value {@link Map} and a custom configuration
	 * {@link Map}
	 *
	 * @param request
	 *            {@link HttpServletRequest} object received from PayPal IPN
	 *            call back.
	 * @param configurationMap
	 *            custom configuration {@link Map}
	 *
	 * @param decoded boolean Representing if the value has been decoded
	 */
	public IPNMessageGAE(HttpServletRequest request,
	                  Map<String, String> configurationMap, boolean decoded) {
		this(request.getParameterMap(), configurationMap, decoded);
	}

	/**
	 * Constructs {@link IPNMessageGAE} using the given {@link HttpServletRequest}
	 * to retrieve the name and value {@link Map} and a custom configuration
	 * {@link Map}
	 *
	 * @param request
	 *            {@link HttpServletRequest} object received from PayPal IPN
	 *            call back.
	 * @param configurationMap
	 *            custom configuration {@link Map}
	 */
	public IPNMessageGAE(HttpServletRequest request,
	                  Map<String, String> configurationMap) {
		this(request.getParameterMap(), configurationMap, true);
	}

	/**
	 * Constructs {@link IPNMessageGAE} using the given {@link Map} for name and
	 * values and a custom configuration {@link Map}
	 *
	 * @param ipnMap
	 *            {@link Map} representing IPN name/value pair
	 * @param configurationMap
	 */
	public IPNMessageGAE(Map<String, String[]> ipnMap,
	                  Map<String, String> configurationMap) {
		this(ipnMap, configurationMap, false);
	}

	/**
	 * Constructs {@link IPNMessageGAE} using the given {@link Map} for name and
	 * values and a custom configuration {@link Map}
	 *
	 * @param ipnMap
	 *            {@link Map} representing IPN name/value pair
	 * @param configurationMap
	 */
	public IPNMessageGAE(Map<String, String[]> ipnMap,
	                  Map<String, String> configurationMap, boolean decoded) {
		this.configurationMap = SDKUtil.combineDefaultMap(configurationMap);
		initialize();
		payload = new StringBuffer("cmd=_notify-validate");
		if (ipnMap != null) {
			String[] encodingParam = ipnMap.get("charset");
			String encoding = encodingParam != null && encodingParam.length > 0 ?
							encodingParam[0] : ENCODING;
			for (Map.Entry<String, String[]> entry : ipnMap.entrySet()) {
				String name = entry.getKey();
				String[] value = entry.getValue();
				try {
					if (decoded) {
						this.ipnMap.put(name, value[0]);
						payload.append("&").append(name).append("=")
										.append(URLEncoder.encode(value[0], encoding));
					} else {
						this.ipnMap.put(name,
										URLDecoder.decode(value[0], encoding));
						payload.append("&").append(name).append("=")
										.append(value[0]);
					}
				} catch (Exception e) {
					LoggingManager.debug(IPNMessageGAE.class, e.getMessage());
				}
			}
		}
	}

	/**
	 * This method post back ipn payload to PayPal system for verification
	 */
	public boolean validate() {
		Map<String, String> headerMap = new HashMap<String, String>();
		URL url = null;
		String res = Constants.EMPTY_STRING;
		HttpConnection connection = ConnectionManager.getInstance()
						.getConnection(httpConfiguration);
		log.info("Connection type: google App Engine: " + (httpConfiguration.isGoogleAppEngine()));

		try {

			connection.createAndconfigureHttpConnection(httpConfiguration);
			url = new URL(this.ipnEndpoint);
			log.info("IPN endpoint: " + this.ipnEndpoint);
			headerMap.put("Host", url.getHost());
			res = Constants.EMPTY_STRING;
			if (!this.isIpnVerified) {
				log.info("Payload: " + payload.toString());
				res = connection.execute(null, payload.toString(), headerMap);
				log.info("Response: " + res);
			}

		} catch (Exception e) {
			log.log(Level.SEVERE, e.getMessage(), e);
		}

		// check notification validation
		if (res.equals("VERIFIED")) {
			isIpnVerified = true;
		}

		return isIpnVerified;
	}

	/**
	 * @return Map of IPN name/value parameters
	 */
	public Map<String, String> getIpnMap() {
		return ipnMap;
	}

	/**
	 * @param ipnName
	 * @return IPN value for corresponding IpnName
	 */
	public String getIpnValue(String ipnName) {

		return this.ipnMap.get(ipnName);

	}

	/**
	 * @return Transaction Type (eg: express_checkout, cart, web_accept)
	 */
	public String getTransactionType() {
		return this.ipnMap.containsKey("txn_type") ? this.ipnMap
						.get("txn_type") : this.ipnMap.get("transaction_type");
	}

	private String getIPNEndpoint() {
		String ipnEPoint = null;
		ipnEPoint = configurationMap.get(Constants.IPN_ENDPOINT);
		if (ipnEPoint == null) {
			String mode = configurationMap.get(Constants.MODE);
			if (mode != null
							&& (Constants.SANDBOX.equalsIgnoreCase(configurationMap
							.get(Constants.MODE).trim()))) {
				ipnEPoint = Constants.IPN_SANDBOX_ENDPOINT;
			} else if (mode != null
							&& (Constants.LIVE.equalsIgnoreCase(configurationMap.get(
							Constants.MODE).trim()))) {
				ipnEPoint = Constants.IPN_LIVE_ENDPOINT;
			}
		}
		return ipnEPoint;
	}

	public String getPayload() {
		return payload.toString();
	}
}

**Comment by juwlee** [comment]
@dincek thanks for suggestion. Since you already seem to know what is going on and have the fix, have you considered sending this in the form of [pull request](https://help.github.com/articles/using-pull-requests/)? That would be easier to compare the code change and review.

**Comment by dincek** [comment]
@juwlee I added pull request with fix for the problem

**Comment by juwlee** [comment]
Thank you @dincek . #57 has been merged.
