### ISSUE TITLE
Resource loading fix as in PayPal-Java-SDK

### ISSUE THREAD

**Issue by Grubsi** [paypal/sdk-core-java#58]
The ResourceLoader cannot handle paths with whitespaces.
Please update the ResourceLoader class as in the PayPal-Java-SDK: https://github.com/paypal/PayPal-Java-SDK/commit/4f6c47675ed8e6201c172d6aa9c3a8e5d3b8286c
Thank You!

**Comment by bluk** [comment]
@Grubsi This should be resolved in [v1.7.1](https://github.com/paypal/sdk-core-java/releases/tag/v1.7.1).  Thanks.
